# Generated by Django 5.1.1 on 2024-10-08 11:09

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_food', '0002_alter_fooditem_available_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='available_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 11, 9, 46, 562894, tzinfo=datetime.timezone.utc)),
        ),
    ]
