# Generated by Django 5.1.2 on 2024-10-10 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_food', '0006_alter_fooditem_available_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='available_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 9, 0, 27, 745184, tzinfo=datetime.timezone.utc)),
        ),
    ]
