# Generated by Django 5.1.2 on 2024-10-14 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_food', '0008_alter_fooditem_available_until_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='available_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 8, 58, 46, 315973, tzinfo=datetime.timezone.utc)),
        ),
    ]
