# Generated by Django 5.1.2 on 2024-10-14 09:04

import share_food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_food', '0009_alter_fooditem_available_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='available_until',
            field=models.DateTimeField(default=share_food.models.FoodItem.default_available_until),
        ),
    ]
